### ISSUE TITLE
Consider moving to go-graphite org?

### ISSUE THREAD

**Issue by Felixoid** [go-graphite/graphite-ch-optimizer#24]
Hello dear colleagues. 

I thought, maybe you'd want to consider moving this repo to https://github.com/go-graphite? The organization already maintains many products like https://github.com/go-graphite/carbonapi, https://github.com/go-graphite/graphite-clickhouse etc.

This repo fits it very well, and as a bonus community would get packages pushed to Deb and RPM repositories.

What do you think?

**Comment by Felixoid** [comment]
Hey-hey @raimund-s and @ragged, are you right persons to ask?

**Comment by Felixoid** [comment]
@kofrezo, could you maybe suggest somebody to ask?

**Comment by kofrezo** [comment]
Talked to @raimund-s we are fine with it.

**Comment by kofrezo** [comment]
I guess we need somebody on the other end @Felixoid to transfer the repository. Can you coordinate please:
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#repository-transfers-and-organizations

**Comment by Felixoid** [comment]
@Civil can transfer the repo. Do I understand it correctly, that he needs admin rights here?

**Comment by Felixoid** [comment]
Or is it simpler to give you a temporary permission to create repos in go-graphite, maybe?

**Comment by Civil** [comment]
@kofrezo I've sent an invite.

**Comment by kofrezo** [comment]
All done. Feel free to remove me from the organisation again.
![Screenshot From 2024-11-18 18-37-48](https://github.com/user-attachments/assets/b98ea07d-eaef-4b37-a4c5-a18821e12157)

**Comment by Felixoid** [comment]
Thank you, @kofrezo and @raimund-s. I am much obliged!

**Comment by Civil** [comment]
> All done. Feel free to remove me from the organisation again.


Thank you very much! I've moved you to "Member" of the go-graphite org and explicitly made you Admin of graphite-ch-optimizer repo.

**Comment by Felixoid** [comment]
@kofrezo Hey Daniel, Merry X-mas!

I am curious: do you need admin access to the repo? Do you plan to contribute here?
