### ISSUE TITLE
Docker images appear to be missing

### ISSUE THREAD

**Issue by ikosenn** [go-graphite/graphite-ch-optimizer#25]
Docker images from the previous repo appear to be missing in: https://hub.docker.com/r/innogames/graphite-ch-optimizer

**Comment by Felixoid** [comment]
That's unfortunate. I'll try to create the images in ghcr.io asap

**Comment by Felixoid** [comment]
It looks like InnoGames doesn't have any image anymore https://hub.docker.com/u/innogames

**Comment by ikosenn** [comment]
Thank you @Felixoid

**Comment by Felixoid** [comment]
You can build your own image from #26, at least the process works good there already.
